### ISSUE TITLE
这些音乐资源是如何获取的？

### ISSUE THREAD

**Issue by zbl19962** [helloforrestworld/Vue-music-#1]
这些音乐资源是如何获取的？

**Comment by helloforrestworld** [comment]
请求QQ音乐接口 某些接口需要反向代理 代码都在api文件夹内

**Comment by yangguoe** [comment]
我copy了代码，可是请求不成功，如何启动prod.server.js呢

**Comment by helloforrestworld** [comment]
npm i 安装依赖了吗；
然后npm run dev 在本地8080端口就能打开；
那个prod.server.js是我用来测试打包后的文件；

在 2018-09-03 14:53:08，"guoe" <notifications@github.com> 写道：


我copy了代码，可是请求不成功，如何启动prod.server.js呢
