### ISSUE TITLE
the songurl can not request

### ISSUE THREAD

**Issue by yangguoe** [helloforrestworld/Vue-music-#2]
i can not request ths songsurl ?can you tell me why?
it always tips xhr.js?ec6c:178 POST http://localhost:8080/api/getPurlUrl 404 (Not Found)
my codes is introduce youer prod.server.js and handlesongurl.js ;
the codes detail is:

    getSingerDetail(this.singer.id).then((res)=>{
            if (res.code === ERR_OK) {
              // this.songs = this._normalizeSongs(res.data.list)
              // console.log(this.songs)
              processSongsUrl(this._normalizeSongs(res.data.list)).then((songs) => {
                console.log('7777')
                this.songs = songs;
                console.log(this.songs);
              });
            }
          })

**Comment by helloforrestworld** [comment]
Did you use expres Router correctly ?
